[
  {
    id: 1,
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    firstName: "Aarav",
    lastName: "Sharma",
    email: "aarav.sharma@example.com",
    contactNumber: "+91-9876543210",
    age: 28,
    job: "Frontend Developer",
    salary: 65000,
    address: "Bangalore, Karnataka, India",
  },
  {
    id: 2,
    imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    firstName: "Priya",
    lastName: "Nair",
    email: "priya.nair@example.com",
    contactNumber: "+91-9876543211",
    age: 26,
    job: "UI/UX Designer",
    salary: 60000,
    address: "Kochi, Kerala, India",
  },
  {
    id: 3,
    imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    firstName: "Rahul",
    lastName: "Verma",
    email: "rahul.verma@example.com",
    contactNumber: "+91-9876543212",
    age: 32,
    job: "Backend Developer",
    salary: 85000,
    address: "Pune, Maharashtra, India",
  },
  {
    id: 4,
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    firstName: "Sneha",
    lastName: "Patel",
    email: "sneha.patel@example.com",
    contactNumber: "+91-9876543213",
    age: 29,
    job: "Full Stack Developer",
    salary: 90000,
    address: "Ahmedabad, Gujarat, India",
  },
  {
    id: 5,
    imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    firstName: "Mohit",
    lastName: "Singh",
    email: "mohit.singh@example.com",
    contactNumber: "+91-9876543214",
    age: 35,
    job: "Project Manager",
    salary: 120000,
    address: "Noida, Uttar Pradesh, India",
  },
  {
    id: 6,
    imageUrl: "https://randomuser.me/api/portraits/women/6.jpg",
    firstName: "Ananya",
    lastName: "Iyer",
    email: "ananya.iyer@example.com",
    contactNumber: "+91-9876543215",
    age: 27,
    job: "QA Engineer",
    salary: 55000,
    address: "Chennai, Tamil Nadu, India",
  },
  {
    id: 7,
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    firstName: "Kunal",
    lastName: "Mehta",
    email: "kunal.mehta@example.com",
    contactNumber: "+91-9876543216",
    age: 31,
    job: "DevOps Engineer",
    salary: 95000,
    address: "Mumbai, Maharashtra, India",
  },
  {
    id: 8,
    imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
    firstName: "Pooja",
    lastName: "Kapoor",
    email: "pooja.kapoor@example.com",
    contactNumber: "+91-9876543217",
    age: 24,
    job: "HR Executive",
    salary: 45000,
    address: "Delhi, India",
  },
  {
    id: 9,
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    firstName: "Rohit",
    lastName: "Malhotra",
    email: "rohit.malhotra@example.com",
    contactNumber: "+91-9876543218",
    age: 34,
    job: "Business Analyst",
    salary: 80000,
    address: "Gurgaon, Haryana, India",
  },
  {
    id: 10,
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    firstName: "Neha",
    lastName: "Joshi",
    email: "neha.joshi@example.com",
    contactNumber: "+91-9876543219",
    age: 30,
    job: "Product Manager",
    salary: 110000,
    address: "Hyderabad, Telangana, India",
  },
  {
    id: 11,
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    firstName: "Sahil",
    lastName: "Khan",
    email: "sahil.khan@example.com",
    contactNumber: "+91-9876543220",
    age: 25,
    job: "Junior Developer",
    salary: 40000,
    address: "Indore, Madhya Pradesh, India",
  },
  {
    id: 12,
    imageUrl: "https://randomuser.me/api/portraits/women/10.jpg",
    firstName: "Aditi",
    lastName: "Rao",
    email: "aditi.rao@example.com",
    contactNumber: "+91-9876543221",
    age: 33,
    job: "Tech Lead",
    salary: 130000,
    address: "Bangalore, Karnataka, India",
  },
];
